/**
 * Generate Tailwind theme CSS for use alongside converted Panda components
 *
 * This creates a CSS file with:
 * 1. Tailwind's CSS custom properties (colors, spacing, fonts, etc.)
 * 2. Base/preflight styles
 * 3. Any extracted custom styles from the original HTML
 */

import { compile } from "tailwindcss";
import { readFileSync } from "fs";
import { dirname, join } from "pathe";
import { getTailwindDir } from "./resolve-utils";

// Load a stylesheet from the tailwindcss package or filesystem
async function loadStylesheet(id: string, base: string): Promise<{ path: string; content: string; base: string }> {
  const twDir = getTailwindDir();

  if (id === "tailwindcss" || id === "tailwindcss/index.css") {
    const path = join(twDir, "index.css");
    const content = readFileSync(path, "utf-8");
    return { path, content, base: twDir };
  }

  if (id === "tailwindcss/preflight" || id === "tailwindcss/preflight.css") {
    const path = join(twDir, "preflight.css");
    const content = readFileSync(path, "utf-8");
    return { path, content, base: twDir };
  }

  if (id === "tailwindcss/theme" || id === "tailwindcss/theme.css") {
    const path = join(twDir, "theme.css");
    const content = readFileSync(path, "utf-8");
    return { path, content, base: twDir };
  }

  if (id === "tailwindcss/utilities" || id === "tailwindcss/utilities.css") {
    const path = join(twDir, "utilities.css");
    const content = readFileSync(path, "utf-8");
    return { path, content, base: twDir };
  }

  try {
    const fullPath = join(base, id);
    const content = readFileSync(fullPath, "utf-8");
    return { path: fullPath, content, base: dirname(fullPath) };
  } catch {
    throw new Error(`Cannot load stylesheet: ${id} from ${base}`);
  }
}

export interface ThemeCssOptions {
  /** Include Tailwind's preflight/reset styles */
  includePreflight?: boolean | undefined;
  /** Include the full theme (all CSS variables) */
  includeTheme?: boolean | undefined;
  /** Custom CSS to append (e.g., from extracted <style> tags) */
  customCss?: string | undefined;
  /** CSS classes that need definitions (unconverted classes) */
  customClasses?: string[] | undefined;
}

/**
 * Generate Tailwind's theme CSS with all CSS custom properties
 */
export async function generateTailwindThemeCss(options: ThemeCssOptions = {}): Promise<string> {
  const { includePreflight = true, includeTheme = true, customCss = "", customClasses = [] } = options;

  // Build the Tailwind CSS input
  const cssInput = '@import "tailwindcss";';

  // Compile to get the full CSS
  const compiled = await compile(cssInput, { loadStylesheet });

  // Build with candidates that force theme generation
  // Use common utilities to ensure theme variables are included
  const themeCandidates = [
    // Colors
    "text-gray-50",
    "text-gray-100",
    "text-gray-200",
    "text-gray-300",
    "text-gray-400",
    "text-gray-500",
    "text-gray-600",
    "text-gray-700",
    "text-gray-800",
    "text-gray-900",
    "bg-white",
    "bg-black",
    // Spacing
    "p-0",
    "p-1",
    "p-2",
    "p-4",
    "p-8",
    "p-12",
    "p-16",
    "p-20",
    "p-24",
    // Font sizes
    "text-xs",
    "text-sm",
    "text-base",
    "text-lg",
    "text-xl",
    "text-2xl",
    "text-3xl",
    "text-4xl",
    "text-5xl",
    "text-6xl",
    "text-7xl",
    "text-8xl",
    // Font weights
    "font-thin",
    "font-light",
    "font-normal",
    "font-medium",
    "font-semibold",
    "font-bold",
    "font-extrabold",
    // Line heights
    "leading-none",
    "leading-tight",
    "leading-snug",
    "leading-normal",
    "leading-relaxed",
    "leading-loose",
    // Letter spacing
    "tracking-tighter",
    "tracking-tight",
    "tracking-normal",
    "tracking-wide",
    "tracking-wider",
    "tracking-widest",
    // Border radius
    "rounded-none",
    "rounded-sm",
    "rounded",
    "rounded-md",
    "rounded-lg",
    "rounded-xl",
    "rounded-2xl",
    "rounded-full",
    // Shadows
    "shadow-sm",
    "shadow",
    "shadow-md",
    "shadow-lg",
    "shadow-xl",
    // Containers
    "max-w-sm",
    "max-w-md",
    "max-w-lg",
    "max-w-xl",
    "max-w-2xl",
    "max-w-3xl",
    "max-w-4xl",
    "max-w-5xl",
    "max-w-6xl",
    "max-w-7xl",
  ];

  const css = compiled.build(themeCandidates);

  // Build the output
  const output: string[] = [];

  output.push(`/**
 * Tailwind CSS Theme Variables
 * Generated by tw2panda for use with converted Panda CSS components
 *
 * Import this file in your app to provide CSS variable fallbacks:
 * import "./tailwind-theme.css";
 */
`);

  // Add the compiled CSS (includes theme variables and preflight if enabled)
  if (includeTheme || includePreflight) {
    output.push(css);
  }

  // Add placeholder definitions for custom classes
  if (customClasses.length > 0) {
    output.push(`
/* ========================================
 * Custom Classes (need manual definition)
 * These classes were found in your HTML but
 * couldn't be converted to Panda CSS.
 * ======================================== */
`);
    for (const cls of customClasses) {
      // Skip classes that look like they have values (e.g., "hidden={true}")
      if (cls.includes("=") || cls.includes("{")) continue;

      output.push(`.${cls} {
  /* TODO: Add styles for .${cls} */
}
`);
    }
  }

  // Add custom CSS from extracted <style> tags
  if (customCss) {
    output.push(`
/* ========================================
 * Custom Styles (from original HTML)
 * ======================================== */
${customCss}
`);
  }

  return output.join("\n");
}

/**
 * Generate a minimal theme CSS with just the CSS custom properties
 * (no utility classes, just the :root variables)
 */
export async function generateThemeVariablesOnly(options: ThemeCssOptions = {}): Promise<string> {
  const { customCss = "", customClasses = [] } = options;

  // Compile Tailwind to get theme
  const compiled = await compile('@import "tailwindcss";', { loadStylesheet });

  // Build with minimal candidates to get theme variables
  const css = compiled.build(["text-black"]);

  // Extract just the :root and @property declarations
  const lines = css.split("\n");
  const themeLines: string[] = [];
  let inRoot = false;
  let inProperty = false;
  let braceCount = 0;

  for (const line of lines) {
    // Track @property blocks
    if (line.trim().startsWith("@property")) {
      inProperty = true;
      braceCount = 0;
    }

    if (inProperty) {
      themeLines.push(line);
      braceCount += (line.match(/{/g) || []).length;
      braceCount -= (line.match(/}/g) || []).length;
      if (braceCount <= 0) {
        inProperty = false;
      }
      continue;
    }

    // Track :root block
    if (line.trim().startsWith(":root")) {
      inRoot = true;
      braceCount = 0;
    }

    if (inRoot) {
      themeLines.push(line);
      braceCount += (line.match(/{/g) || []).length;
      braceCount -= (line.match(/}/g) || []).length;
      if (braceCount <= 0) {
        inRoot = false;
      }
    }
  }

  const output: string[] = [];

  output.push(`/**
 * Tailwind CSS Theme Variables (minimal)
 * Contains only CSS custom properties for token fallbacks
 */
`);

  output.push(themeLines.join("\n"));

  // Add custom class placeholders
  if (customClasses.length > 0) {
    output.push(`
/* Custom Classes */
`);
    for (const cls of customClasses) {
      if (cls.includes("=") || cls.includes("{")) continue;
      output.push(`.${cls} { /* TODO */ }\n`);
    }
  }

  if (customCss) {
    output.push(`
/* Original Custom Styles */
${customCss}
`);
  }

  return output.join("\n");
}
